homesoft_torrent_streamer:
    resource: "@HomesoftTorrentStreamerBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"